# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.4
FROM node:lts-alpine AS builder
WORKDIR /app
# Install build dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
COPY index.ts .
RUN npm ci && npm run build

FROM node:lts-alpine
WORKDIR /app
# Copy built files and production dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

# Default command to run the MCP server
ENTRYPOINT ["node", "dist/index.js"]
